### ISSUE TITLE
Error when only adding the dependency

### ISSUE THREAD

**Issue by straumat** [theborakompanioni/bitcoin-spring-boot-starter#110]
If I only add the dependency to my project (without any modification):
```
<dependency>
   <groupId>io.github.theborakompanioni</groupId>
   <artifactId>spring-lnurl-auth-starter</artifactId>
   <version>${bitcoin-spring-boot-starter.version}</version>
</dependency>
```

And I run my existing tests, I get this error:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
The dependencies of some of the beans in the application context form a cycle:
┌──->──┐
|  k1Manager defined in class path resource [org/tbk/spring/lnurl/config/K1AutoConfiguration.class]
└──<-──┘
```

If I add this in any `@Configuration` class, it works:
```
@Bean
K1Manager k1Manager() {
   return new SimpleK1Manager();
}
```

I don't have this problem with other bean in your spring boot starter so maybe it's a configuration issue on your side?
This bug is very very very minor so no problem if not corrected.

_For information, my project is a also a spring boot starter._

**Comment by theborakompanioni** [comment]
Thanks @straumat. Seems like a bug!
Will try to reproduce and report back when I am at my workstation again (hopefully tomorrow). :pray:
