### ISSUE TITLE
SimpleLinkingKey not found when used in spring boot starter.

### ISSUE THREAD

**Issue by straumat** [theborakompanioni/bitcoin-spring-boot-starter#112]
I'm building a Spring boot starter including `spring-lnurl-auth-starter`.

In my spring boot starter tests, I can do this: 
```java
LinkingKey linkingKeyTest1 = SimpleLinkingKey.fromHex("02c3b844b8104f0c1b15c507774c9ba7fc609f58f343b9b149122e944dd20c9362");`
```

In my spring boot starter code, I can't do the same thing:
```java
LinkingKey linkingKeyTest1 = SimpleLinkingKey.fromHex("02c3b844b8104f0c1b15c507774c9ba7fc609f58f343b9b149122e944dd20c9362");`
```

because I get this error: `java: package org.tbk.lnurl.simple.auth does not exist`

I'm forced to add this to my POM:
```xml
<dependency>
   <groupId>io.github.theborakompanioni</groupId>
   <artifactId>lnurl-simple</artifactId>
   <version>0.11.0</version>
</dependency>
```

**Comment by theborakompanioni** [comment]
This is done intentionally. The idea is that the "simple" packages are just the most basic implementation of the functionality. If you really want to use them, you should declare them as dependency explicitly.

At least that's the concept... do you think it's a bad idea?

**Comment by straumat** [comment]
Nope, i just wanted to be sure it was intentional because it's not described in the tutorial :)

In fact, what I find strange is that you asl for to implement this method:
```java
Optional<LinkingKey> findPairedLinkingKeyByK1(K1 k1);
```

And without `SimpleLinkingKey`, I don't know how to return a `LinkingKey`.

I add this step to the tutorial
Thx for the release :)

**Comment by theborakompanioni** [comment]
> Nope, i just wanted to be sure it was intentional because it's not described in the tutorial :)
> 
> In fact, what I find strange is that you ask for `LinkingKey` to implement this method:
> 
> ```java
> Optional<LinkingKey> findPairedLinkingKeyByK1(K1 k1);
> ```
> 
> And without `SimpleLinkingKey`, I don't know how to return a `LinkingKey`.
> 
> I add this step to the tutorial Thx for the release :)

Hmm.. that's true. I mean.. you do not really need access to `SimpleLinkingKey` if you use the in-built default `InMemoryLnurlAuthPairingService`.. and "enterprise" apps would probably provide their own implementations. However.. I'd see a value in adding it when you use the `spring-lnurl-auth-starter` (and hence, opting into "automagic" setup).
Would you say it is sufficient to add it to the starter module only (not the `spring-lnurl-auth-autoconfigure` module)?

**Comment by theborakompanioni** [comment]
> > Nope, i just wanted to be sure it was intentional because it's not described in the tutorial :)
> > In fact, what I find strange is that you ask for `LinkingKey` to implement this method:
> > ```java
> > Optional<LinkingKey> findPairedLinkingKeyByK1(K1 k1);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And without `SimpleLinkingKey`, I don't know how to return a `LinkingKey`.
> > I add this step to the tutorial Thx for the release :)
> 
> Hmm.. that's true. I mean.. you do not really need access to `SimpleLinkingKey` if you use the in-built default `InMemoryLnurlAuthPairingService`.. and "enterprise" apps would probably provide their own implementations. However.. I do see a value in adding it when you use the `spring-lnurl-auth-starter` (and hence, opting into "automagic" setup). Would you say it is sufficient to add it to the starter module only (not the `spring-lnurl-auth-autoconfigure` module)?

**Comment by straumat** [comment]
Sorry, i'm not yet capable to replay, i first need to understand more :D

I know I have to implement `Optional<LinkingKey> findPairedLinkingKeyByK1(K1 k1);`  from `LnurlAuthPairingService` but I don't understand yet what calls this method and why.

With my understanding (partial for the moment), your framework needs a cache manager to store the `k1` proposed for logins, then, when the wallet will reply with the k1 signed and the public key, you will do the verification by calling the `pairK1WithLinkingKey()` I implemented.

`pairK1WithLinkingKey()` returns true if user has been created or found (i guess). 

It's all I could guess for the moment, so I did not understand when and why `Optional<LinkingKey> findPairedLinkingKeyByK1(K1 k1);`  is called :)

**Comment by theborakompanioni** [comment]
I think I can image where the missing link is.
It might also be that the current approach is a bit weak, but stay with me.

The `LnurlAuthPairingService` is the class that brings the wallet and the web session together.

There are two filters with respective `AuthenticationProvider`:
- `LnurlAuthWalletAuthenticationProvider` invoked by the WALLET which calls `pairK1WithLinkingKey`
- `LnurlAuthSessionAuthenticationProvider` invoked by BROWSER (e.g. by polling) which calls `findPairedLinkingKeyByK1`

After that - an attempt is made to receive a user (in `AbstractTokenAuthenticationProvider` which both provider inherit from) via `userDetailsService.loadUserByUsername(<linking_key_in_hex>)`.

I hope that clarifies the current approach.

What I am wondering now, if this can be simplified by defining `LnurlAuthPairingService` in the following way:

```java
public interface LnurlAuthPairingService {

    UserDetails markUserWithLinkingKeyAndK1(LinkingKey linkingKey, K1 k1); // called by wallet flow

    Optional<UserDetails> findPairedUserByK1(K1 k1); // called by web session flow
}
```

I have not thought this through entirely. It will tightly couple the Pairing Service to UserDetails.. not sure if this is good, but it definitely looks easier for downstream users.

**Comment by straumat** [comment]
Thanks !
` UserDetails markUserWithLinkingKeyAndK1(LinkingKey linkingKey, K1 k1);` will make lots of sense !

**Comment by theborakompanioni** [comment]
With the latest changes in #117 and the introduction of `LnurlAuthUserPairingService`, importing `lnurl-simple` should not be strictly necessary anymore.

**Comment by straumat** [comment]
I think it's not necessary anymore
But as I need to build my own [k1Manager](https://github.com/royllo/explorer/blob/1c8ada67329a5586e4af7699754ab8c371143f5f/backend/explorer-core/autoconfigure/src/main/java/org/royllo/explorer/core/service/util/DatabaseK1Manager.java#L19), I'm forced to import `lnurl-simple`.
But I don't think it's a bug, I think you can close this issue.

**Comment by theborakompanioni** [comment]
> I think it's not necessary anymore But as I need to build my own [k1Manager](https://github.com/royllo/explorer/blob/1c8ada67329a5586e4af7699754ab8c371143f5f/backend/explorer-core/autoconfigure/src/main/java/org/royllo/explorer/core/service/util/DatabaseK1Manager.java#L19), I'm forced to import `lnurl-simple`. But I don't think it's a bug, I think you can close this issue.

`lnurl-simple` is now imported in `spring-lnurl-auth-starter` with 9430e5a040b5a8bddf2b9d32b34da6a37627ff87.
