### ISSUE TITLE
Using SNAPSHOT release

### ISSUE THREAD

**Issue by straumat** [theborakompanioni/bitcoin-spring-boot-starter#118]
HI, to test your new development and close some issues, I wanted to move to `0.13.0-SNAPSHOT`

I made this change to maven:
```xml
<dependency>
   <groupId>io.github.theborakompanioni</groupId>
   <artifactId>spring-lnurl-auth-starter</artifactId>
   <version>0.13.0-SNAPSHOT</version>
</dependency>
```

And I added:
```
    <repositories>
        <repository>
            <id>snapshot-repo</id>
            <url>https://s01.oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
```

But I get this message: `Dependency 'io.github.theborakompanioni:spring-lnurl-auth-starter:0.13.0-SNAPSHOT' not found`
What did I get wrong?

**Comment by theborakompanioni** [comment]
Hey @straumat!

You did nothing wrong. Snapshots are not published to Maven Central.
You can use jitpack to try out individual PRs or branches (e.g. `devel` branch).
Be aware, that the name is different.

```xml
<repositories>
   <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
   </repository>
</repositories>
```

```xml
<dependency>
   <groupId>com.github.theborakompanioni.bitcoin-spring-boot-starter</groupId>
   <artifactId>spring-lnurl-auth-starter</artifactId>
   <version>devel-SNAPSHOT</version>
</dependency>
```

**Comment by straumat** [comment]
It works ! thanks
For information, i thought it was snoatype because I saw this in your repo:
[https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/7397e82dd78e770b4033b1a876537aef0ab774ab/publish.gradle#L36](https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/7397e82dd78e770b4033b1a876537aef0ab774ab/publish.gradle#L36)

Also, to make it work, I had to remove something that was  working before:
```java
                .exceptionHandling((exceptionHandling) -> exceptionHandling
                        .accessDeniedPage(ERROR_403_PAGE)
                        .authenticationEntryPoint((request, response, authenticationException) -> response.sendRedirect(LNURL_AUTH_LOGIN_PAGE_PATH))
                )
```
