### ISSUE TITLE
Blog post review

### ISSUE THREAD

**Issue by straumat** [theborakompanioni/bitcoin-spring-boot-starter#119]
Hi!

Thanks again for your help.

I finished the blog post; Do you thing you could take a look at it before I publish it?
I don't want people to get the wrong idea about your project.
https://github.com/royllo/explorer/blob/development/docs/design/lnurl-auth/README.md

I have one last question:

**K1 exchange**
I read in the documentation that the wallet will call the server URL login with this:
`sig=<hex(sign(utf8ToBytes(k1), linkingPrivKey))>&key=<hex(linkingKey)>`

From what I see, the server will receive the signed k& and the public linking key.
How do you, on the server side, make the link between the k1 your provided and the signed k1 you received ?

**Comment by theborakompanioni** [comment]
> Hi!
> 
> Thanks again for your help.

Team effort :muscle: 

> I finished the blog post; Do you thing you could take a look at it before I publish it? I don't want people to get the wrong idea about your project. https://github.com/royllo/explorer/blob/development/docs/design/lnurl-auth/README.md

Looks good! So nice!

Maybe a hint that the module is actually still in "incubator" mode.
I want to make it a first class citizen once the "default login page" can be customized (currently, it is basically uncustomizable).

> I have one last question:
> 
> **K1 exchange** I read in the documentation that the wallet will call the server URL login with this: `sig=<hex(sign(utf8ToBytes(k1), linkingPrivKey))>&key=<hex(linkingKey)>`
> 
> From what I see, the server will receive the signed k& and the public linking key. How do you, on the server side, make the link between the k1 your provided and the signed k1 you received ?

In your quote you forgot `<LNURL_existing_query_parameters>` which includes the plain `k1` value as well.
Of course, to verify the signature one needs the `k1`, `sig` and `pubkey`!
May that is also worth adapting in the blog post!

So the called url actually includes `tag`, `k1`, `sig`, `key` and optionally `action`.
