### ISSUE TITLE
Tor new IP on each request or at will

### ISSUE THREAD

**Issue by SpiReCZ** [theborakompanioni/bitcoin-spring-boot-starter#36]
**Is your feature request related to a problem? Please describe.**
I want to use this Tor library to make requests to single/similar URL multiple times from different IP.
Each time the URL will be called, it requires new IP since the service that will be accessed limits usage per IP.
What is not required for this to work is speed. If i were to make 10 requests to the URL it would be fine if accessing all those took ~1-2 minutes.

**A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
Currently this library or it's dependencies does not provide a way to restart Tor connection in runtime without killing the Tor process.

**Describe the solution you'd like**
I really like the solution i've seen used in python stem library.
https://stem.torproject.org/faq.html#how-do-i-reload-my-torrc
```
from stem import Signal
from stem.control import Controller

with Controller.from_port(port = 9051) as controller:
  controller.authenticate()
  controller.signal(Signal.HUP)
```

As the documentation states, this can be achieved via sending a singla `RELOAD: HUP`. https://github.com/torproject/torspec/blob/main/control-spec.txt

**A clear and concise description of what you want to happen.**
Obtain new IP address.

**Describe alternatives you've considered**
- Abillity to call some function/method `tor.reload()` to obtain new IP address.
- Or abillity to create new instance of Tor Controller without killing it's Tor process to obtain new IP address like the python stem library is able to do..

**Additional context**
I tried sending the `RELOAD` signal with local build of `com.github.bisq-network.netlayer:tor,` but that only closed Tor circuits and the Tor Socks port got closed as well (without opening a new one).
I am not exactly sure what should be done in the terms of this/dependant java implementations to open new Tor Socks port.
Maybe my attempt with the `RELOAD` was wrong in the first place, but it works fine here: https://github.com/setnicka/ulozto-downloader/blob/0e3b810f7676f543bf403f2f6b998c9ea02fb893/uldlib/torrunner.py#L59.

I also tried using `NEWNYM`, but that does not provide deterministic outcome, since the new circuits provided can ultimately have the same IP or the signal is ignored by Tor at some point.

**Comment by theborakompanioni** [comment]
Thank you for your request. I appreciate all the thought you put into it and you took the time to lay them out in a very comprehensible way.

> I also tried using `NEWNYM`, but that does not provide deterministic outcome, since the new circuits provided can ultimately have the same IP or the signal is ignored by Tor at some point.

Yeah, it seems this is the way how Tor inherently works. On the document you linked, you can find this quote:
> An important thing to note is that a new circuit does not necessarily mean a new IP address. Paths are randomly selected based on heuristics like speed and stability. There are only so many large exits in the Tor network, so it's not uncommon to reuse an exit you have had previously.

Also:

> Tor does not have a method for cycling your IP address. This is on purpose, and done for a couple reasons. The first is that this capability is usually requested for not-so-nice reasons such as ban evasion or SEO. Second, repeated circuit creation puts a very high load on the Tor network, so please don't!

Then, it mentions `torrc` config `MaxCircuitDirtiness`, which states the time in seconds when a circuit becomes "dirty" and hence a new one is built.

But from [stackoverflow#66634188](https://stackoverflow.com/questions/66634188/tor-does-not-honor-maxcircuitdirtiness):
> Please note that MaxCircuitDirtiness only ensures that a new Tor circuit is created and used, but that does not always imply a new IP (i.e. does not always imply a different "end node" on the new circuit).

So, I think there is no real way to do what you want to achieve, at least not with Tor. Maybe I2P is better suited? I really don't know, as I am not familiar with it.

But, you are right, at first glance, the underlying lib currently does not provide much flexibility in terms of control and customization.
I will see what can be done about this.

**Comment by SpiReCZ** [comment]
Check this out: https://github.com/setnicka/ulozto-downloader/blob/0e3b810f7676f543bf403f2f6b998c9ea02fb893/uldlib/page.py#L242
It is my exact use case scenario.
It also leads to this: https://github.com/setnicka/ulozto-downloader/blob/0e3b810f7676f543bf403f2f6b998c9ea02fb893/uldlib/torrunner.py#L59
(as mentioned in the stem documentation)

Change of the IP may be only a side effect in the end, but in the linked case it is used as change of the IP.

**Comment by theborakompanioni** [comment]
I think you can accomplish it by yourself if you access the `torController` var of an instance of the `Tor` class, e.g.:
```java
Field torControllerField = Tor.class.getDeclaredField("torController");
torControllerField.setAccessible(true);
TorController torController = (TorController) torControllerField.get(yourTorInstance);
// use "signal" to send commands
torController.signal("RELOAD");
torController.signal("HUP");
```

I am very reluctant to expose this object as a spring managed bean, as it is a `protected` member and not intended to be used like this. Maybe this issue is better placed in the library repo: https://github.com/bisq-network/netlayer
If this mechanism is made available for downstream consumers, I am happy to expose it!

What do you say? Does this sound reasonable to you?

**Comment by SpiReCZ** [comment]
I figured RELOAD/HUP does not work with Tor being in Daemon mode..
I will fiddle with it a bit more, but yes the bisq-network library is the one where everything that could be changed is.
It's sad they do not have enabled issues on their github fork and their implementations are pretty locked up and non-configurable.

**Comment by theborakompanioni** [comment]
> I figured RELOAD/HUP does not work with Tor being in Daemon mode.. 

Ah, thanks for the info.

> I will fiddle with it a bit more, but yes the bisq-network library is the one where everything that could be changed is. It's sad they do not have enabled issues on their github fork and their implementations are pretty locked up and non-configurable.

Damn.. you are right. Issues not enabled.. strange. You might be better of writing your own.
Or, if you find a suitable library, let me know - might be beneficial to others as well.

Thank you.

**Comment by SpiReCZ** [comment]
The issue with this and dependant Tor libraries is that they do very little, yet they are seperated. If it was just 1 multi-module separate project just for Tor Java/Kotlin integration it would be cool.
I was lucky to find this library, took me a long time. There are a lot of forks of the original java impl, but every library seems dead and undocumented.

**Comment by SpiReCZ** [comment]
Have you considered to seperate the tor library from this project?

**Comment by theborakompanioni** [comment]
> Have you considered to separate the tor library from this project?

Yes, I thought about that. But in fact, the project is already independent from the other modules and also published to maven central. Do you refer to better discoverability and/or documentation if it is a standalone project? I am certainly not against that at all! Currently, it is all done in a single repo as it is just easier for me to update dependencies or publish releases.

**Comment by SpiReCZ** [comment]
I created a PR: https://github.com/bisq-network/netlayer/pull/13
These contain some fixes and also required changes for my use case.

Desired behavior can be made by:
```
@Configuration
class TorConfig {

    @Bean
    @Throws(IOException::class)
    fun torrc(): Torrc {
        val ports = obtainFreePorts()
        val overrides = LinkedHashMap<String, String>()
        // It is required to set ports manually
        overrides["ControlPort"] = ports.first.toString()
        overrides["SOCKSPort"] = ports.second.toString()
        return Torrc(overrides)
    }

}
```

and extension function:
```
    fun Tor.reload() {
        val torControllerField: Field = Tor::class.java.getDeclaredField("torController")
        torControllerField.isAccessible = true
        val torController: TorController = torControllerField.get(this) as TorController
        torController.setConf("DisableNetwork", "1")
        torController.setConf("DisableNetwork", "0")
    }
```

**Comment by theborakompanioni** [comment]
> Have you considered to separate the tor library from this project?

`spring-tor` has been externalized to https://github.com/theborakompanioni/tor-spring-boot-starter
