### ISSUE TITLE
Not able to build with Java 20

### ISSUE THREAD

**Issue by jump-kick** [theborakompanioni/bitcoin-spring-boot-starter#97]
https://github.com/theborakompanioni/bitcoin-spring-boot-starter/blob/fa324a3b34e7dfe9d6765ab8da2262cef49ba45a/readme.md?plain=1#L117

For a while I tried doing the Gradle build of the project using Java 20, but was only able to build it when I switched to Java 17.  Is there a maximum Java version?

**Comment by theborakompanioni** [comment]
Hey @jump-kick, thanks for the report, brother :orange_heart: 

I assume this has to do with lombok. Can you verify that https://github.com/theborakompanioni/bitcoin-spring-boot-starter/pull/98 works for you? This will test the build with Java 21, which is a LTS release and should be supported. I have not tested it with Java 20, but I suppose it will work too.

Appreciate any and all feedback. Thank you :pray:

**Comment by jump-kick** [comment]
Thanks for the response!  I will verify it, but I'm having trouble checking out the java21 branch for some reason.  Will let you know ASAP

**Comment by jump-kick** [comment]
You must have been right about Lombok!  Yes, the build works on Java 20!  Thanks
